/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaudoCodigoRouteImport } from './routes/laudo.$codigo'
import { Route as AuthenticatedVeiculosRouteImport } from './routes/_authenticated/veiculos'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedVistoriasIndexRouteImport } from './routes/_authenticated/vistorias/index'
import { Route as AuthenticatedVistoriasNovaRouteImport } from './routes/_authenticated/vistorias/nova'
import { Route as AuthenticatedVistoriasIdRouteImport } from './routes/_authenticated/vistorias/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaudoCodigoRoute = LaudoCodigoRouteImport.update({
  id: '/laudo/$codigo',
  path: '/laudo/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVeiculosRoute = AuthenticatedVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVistoriasIndexRoute =
  AuthenticatedVistoriasIndexRouteImport.update({
    id: '/vistorias/',
    path: '/vistorias/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVistoriasNovaRoute =
  AuthenticatedVistoriasNovaRouteImport.update({
    id: '/vistorias/nova',
    path: '/vistorias/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVistoriasIdRoute =
  AuthenticatedVistoriasIdRouteImport.update({
    id: '/vistorias/$id',
    path: '/vistorias/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/laudo/$codigo': typeof LaudoCodigoRoute
  '/vistorias/$id': typeof AuthenticatedVistoriasIdRoute
  '/vistorias/nova': typeof AuthenticatedVistoriasNovaRoute
  '/vistorias/': typeof AuthenticatedVistoriasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/laudo/$codigo': typeof LaudoCodigoRoute
  '/vistorias/$id': typeof AuthenticatedVistoriasIdRoute
  '/vistorias/nova': typeof AuthenticatedVistoriasNovaRoute
  '/vistorias': typeof AuthenticatedVistoriasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/veiculos': typeof AuthenticatedVeiculosRoute
  '/laudo/$codigo': typeof LaudoCodigoRoute
  '/_authenticated/vistorias/$id': typeof AuthenticatedVistoriasIdRoute
  '/_authenticated/vistorias/nova': typeof AuthenticatedVistoriasNovaRoute
  '/_authenticated/vistorias/': typeof AuthenticatedVistoriasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/historico'
    | '/usuarios'
    | '/veiculos'
    | '/laudo/$codigo'
    | '/vistorias/$id'
    | '/vistorias/nova'
    | '/vistorias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/historico'
    | '/usuarios'
    | '/veiculos'
    | '/laudo/$codigo'
    | '/vistorias/$id'
    | '/vistorias/nova'
    | '/vistorias'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/historico'
    | '/_authenticated/usuarios'
    | '/_authenticated/veiculos'
    | '/laudo/$codigo'
    | '/_authenticated/vistorias/$id'
    | '/_authenticated/vistorias/nova'
    | '/_authenticated/vistorias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  LaudoCodigoRoute: typeof LaudoCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laudo/$codigo': {
      id: '/laudo/$codigo'
      path: '/laudo/$codigo'
      fullPath: '/laudo/$codigo'
      preLoaderRoute: typeof LaudoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/veiculos': {
      id: '/_authenticated/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AuthenticatedVeiculosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vistorias/': {
      id: '/_authenticated/vistorias/'
      path: '/vistorias'
      fullPath: '/vistorias/'
      preLoaderRoute: typeof AuthenticatedVistoriasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vistorias/nova': {
      id: '/_authenticated/vistorias/nova'
      path: '/vistorias/nova'
      fullPath: '/vistorias/nova'
      preLoaderRoute: typeof AuthenticatedVistoriasNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vistorias/$id': {
      id: '/_authenticated/vistorias/$id'
      path: '/vistorias/$id'
      fullPath: '/vistorias/$id'
      preLoaderRoute: typeof AuthenticatedVistoriasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVeiculosRoute: typeof AuthenticatedVeiculosRoute
  AuthenticatedVistoriasIdRoute: typeof AuthenticatedVistoriasIdRoute
  AuthenticatedVistoriasNovaRoute: typeof AuthenticatedVistoriasNovaRoute
  AuthenticatedVistoriasIndexRoute: typeof AuthenticatedVistoriasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVeiculosRoute: AuthenticatedVeiculosRoute,
  AuthenticatedVistoriasIdRoute: AuthenticatedVistoriasIdRoute,
  AuthenticatedVistoriasNovaRoute: AuthenticatedVistoriasNovaRoute,
  AuthenticatedVistoriasIndexRoute: AuthenticatedVistoriasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  LaudoCodigoRoute: LaudoCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
